#!/bin/bash
./parser test/test_1.c
./parser test/test_2.c
./parser test/test_3.c
./parser test/test_4.c
./parser test/test_5.c
./parser test/test_6.c
./parser test/test_7.c
./parser test/test_8.c
./parser test/test_9.c
./parser test/test_10.c
./parser test/test_11.c
./parser test/test_12.c
./parser test/test_13.c
./parser test/test_14.c
./parser test/test_15.c
./parser test/test_16.c
./parser test/test_17.c
./parser test/test_18.c
./parser test/test_19.c
./parser test/test_20.c
